=== bvenreply/vespucci-csv-example/dataset-meta.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://vespucci.st.com/svc/schemas/v1alpha1/dataset-meta.schema.json",
    "title": "VespucciInertialCsvDataset",
    "description": "VespucciInertialCsv dataset schema spec",
    "type": "object",
    "required": [
        "name",
        "id"
    ],
    "properties": {
        "name": {
            "type": "string",
            "description": "Human-readable dataset name. No uniqueness requirement"
        },
        "description": {
            "type": "string",
            "description": "Dataset description"
        },
        "id": {
           "type": "string",
           "description": "Unique ID for the dataset" 
        },
        "classes": {
            "type": "array",
            "description": "The full set of ground truth labels used in the dataset",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
        "metadata": {
            "type": "object",
            "description": "Additional opaque unstructured data that may be attached to the dataset",
            "additionalProperties": true
        },
        "data": {
            "type": "array",
            "description": "Array of data items. A sequence of chunks/acquisitions",
            "items": { "$ref": "#/$defs/DataItem" }
        }
    },
    "$defs": {
        "DataItem": {
            "type": "object",
            "description": "Item in the `data` array. Logically equivalent to a `chunk` in the data-api model and roughly equivalent to an *acquisition* (rather, a portion of it that ) in the context of HSDatalog raw logs",
            "properties": {
                "start_time": {
                    "type": "string",
                    "description": "Start timestamp for the data in this item. An ISO8601 millisecond timestamp",
                    "format": "date-time"
                },
                "end_time": {
                    "type": "string",
                    "description": "End timestamp for the data in this item. An ISO 8601 millisecond timestamp",
                    "format": "date-time"
                },
                "class": {
                    "type": "string",
                    "description": "Ground truth label for "
                }
            }
        }
    }

}

=== bvenreply/vespucci-csv-example/datasets/example/dataset-meta.json
{
  "name": "mock-mlc-dataset",
  "description": "Mocked MLC dataset description",
  "id": "eoteayd6ymrkmfvslcb7h6zkk7gmrusl6d4j7po26wdgcephn5gq====",
  "classes": [
    "motion",
    "shaken",
    "stationary_not_upright",
    "stationary_upright"
  ],
  "data": [
    {
      "start_time": "2000-01-01T00:00:36.379Z",
      "end_time": "2000-01-01T01:09:17.000Z",
      "class": "motion",
      "source_blob": {
        "id": "wm4e2fnqozqczib24eqrl3wamzrhjgyxx6qpyze2a7iykpwuhanq====",
        "metadata": {
          "uuid": "09a21eff-1a81-414f-8383-569d36d933f7",
          "name": "20240212_11_34_06",
          "device_description": {
            "part_number": "STEVAL-MKBOXPRO",
            "serial_number": "005100335752501520353339",
            "alias": "STBOX_PRO_001",
            "fw_name": "FP-SNS-DATALOG2_Datalog2",
            "fw_version": "1.2.1"
          }
        }
      },
      "components": [
        {
          "name": "lsm6dsv16x",
          "sensors": [
            {
              "name": "lsm6dsv16x_acc",
              "type": "Acc",
              "config": {
                "odr": {
                  "value": 7680,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 16,
                  "unit": "g"
                }
              }
            },
            {
              "name": "lsm6dsv16x_gyro",
              "type": "Gyro",
              "config": {
                "odr": {
                  "value": 1920,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 2000,
                  "unit": "mdps"
                }
              }
            }
          ]
        }
      ],
      "file": {
        "id": "rhlp4gw62oq37uctkeonbz745cyparaeuc5hdufpfe53sl6rzx6a====",
        "type": "text/csv",
        "extension": "csv",
        "relative_path": "motion/lsm6dsv16x_rhlp4gw6.csv"
      }
    },
    {
      "start_time": "2000-01-01T00:00:36.379Z",
      "end_time": "2000-01-01T00:00:45.283Z",
      "class": "stationary_upright",
      "source_blob": {
        "id": "wm4e2fnqozqczib24eqrl3wamzrhjgyxx6qpyze2a7iykpwuhanq====",
        "metadata": {
          "uuid": "09a21eff-1a81-414f-8383-569d36d933f7",
          "name": "20240212_11_34_06",
          "device_description": {
            "part_number": "STEVAL-MKBOXPRO",
            "serial_number": "005100335752501520353339",
            "alias": "STBOX_PRO_001",
            "fw_name": "FP-SNS-DATALOG2_Datalog2",
            "fw_version": "1.2.1"
          }
        }
      },
      "components": [
        {
          "name": "lsm6dsv16x",
          "sensors": [
            {
              "name": "lsm6dsv16x_acc",
              "type": "Acc",
              "config": {
                "odr": {
                  "value": 7680,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 16,
                  "unit": "g"
                }
              }
            },
            {
              "name": "lsm6dsv16x_gyro",
              "type": "Gyro",
              "config": {
                "odr": {
                  "value": 1920,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 2000,
                  "unit": "mdps"
                }
              }
            }
          ]
        }
      ],
      "file": {
        "id": "ygp7fqe6jmsybmszwjppsqbmejmkt7pz5ksv5u3rfy7qewuehama====",
        "type": "text/csv",
        "extension": "csv",
        "relative_path": "stationary_upright/lsm6dsv16x_ygp7fqe6.csv"

      }
    },
    {
      "start_time": "2000-01-01T00:00:36.379Z",
      "end_time": "2000-01-01T00:00:45.283Z",
      "class": "stationary_not_upright",
      "source_blob": {
        "id": "wm4e2fnqozqczib24eqrl3wamzrhjgyxx6qpyze2a7iykpwuhanq====",
        "metadata": {
          "uuid": "09a21eff-1a81-414f-8383-569d36d933f7",
          "name": "20240212_11_34_06",
          "device_description": {
            "part_number": "STEVAL-MKBOXPRO",
            "serial_number": "005100335752501520353339",
            "alias": "STBOX_PRO_001",
            "fw_name": "FP-SNS-DATALOG2_Datalog2",
            "fw_version": "1.2.1"
          }
        }
      },
      "components": [
        {
          "name": "lsm6dsv16x",
          "sensors": [
            {
              "name": "lsm6dsv16x_acc",
              "type": "Acc",
              "config": {
                "odr": {
                  "value": 7680,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 16,
                  "unit": "g"
                }
              }
            },
            {
              "name": "lsm6dsv16x_gyro",
              "type": "Gyro",
              "config": {
                "odr": {
                  "value": 1920,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 2000,
                  "unit": "mdps"
                }
              }
            }
          ]
        }
      ],
      "file": {
        "id": "klujd6fsvnoggakduuljaznzuzhwuhhk5o5tecneqyta6i2x5p6q====",
        "relative_path": "stationary_not_upright/lsm6dsv16x_klujd6fs.csv",
        "type": "text/csv",
        "extension": "csv"

      }
    },
    {
      "start_time": "2000-01-01T00:00:36.379Z",
      "end_time": "2000-01-01T00:00:45.283Z",
      "class": "shaken",
      "source_blob": {
        "id": "wm4e2fnqozqczib24eqrl3wamzrhjgyxx6qpyze2a7iykpwuhanq====",
        "metadata": {
          "uuid": "09a21eff-1a81-414f-8383-569d36d933f7",
          "name": "20240212_11_34_06",
          "device_description": {
            "part_number": "STEVAL-MKBOXPRO",
            "serial_number": "005100335752501520353339",
            "alias": "STBOX_PRO_001",
            "fw_name": "FP-SNS-DATALOG2_Datalog2",
            "fw_version": "1.2.1"
          }
        }
      },
      "components": [
        {
          "name": "lsm6dsv16x",
          "sensors": [
            {
              "name": "lsm6dsv16x_acc",
              "type": "Acc",
              "config": {
                "odr": {
                  "value": 7680,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 16,
                  "unit": "g"
                }
              }
            },
            {
              "name": "lsm6dsv16x_gyro",
              "type": "Gyro",
              "config": {
                "odr": {
                  "value": 1920,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 2000,
                  "unit": "mdps"
                }
              }
            }
          ]
        }
      ],
      "file": {
        "id": "j3wquxci4yxufcwwv6kaxhkss2rbtymg5dzdkp76yoc7f3qu3vwa====",
        "relative_path": "shaken/lsm6dsv16x_j3wquxci.csv",
        "type": "text/csv",
        "extension": "csv"

      }
    },
    {
      "start_time": "2000-01-01T01:09:17.000Z",
      "end_time": "2000-01-01T00:00:45.283Z",
      "class": "stationary_upright",
      "source_blob": {
        "id": "wm4e2fnqozqczib24eqrl3wamzrhjgyxx6qpyze2a7iykpwuhanq====",
        "metadata": {
          "uuid": "27675a99-3ffe-4cbc-9017-9c333f240a5a",
          "name": "20240212_11_34_06",
          "device_description": {
            "part_number": "STEVAL-MKBOXPRO",
            "serial_number": "005100335752501520353339",
            "alias": "STBOX_PRO_001",
            "fw_name": "FP-SNS-DATALOG2_Datalog2",
            "fw_version": "1.2.1"
          }
        }
      },
      "components": [
        {
          "name": "lsm6dsv16x",
          "sensors": [
            {
              "name": "lsm6dsv16x_acc",
              "type": "Acc",
              "config": {
                "odr": {
                  "value": 480,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 4,
                  "unit": "g"
                }
              }
            },
            {
              "name": "lsm6dsv16x_gyro",
              "type": "Gyro",
              "config": {
                "odr": {
                  "value": 3840,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 4000,
                  "unit": "mdps"
                }
              }
            }
          ]
        }
      ],
      "file": {
        "id": "zjdmedamwqxogv5xeuh6bky75cvpqj77y72wdw63maqcpc2o5h4q====",
        "relative_path": "stationary_upright/lsm6dsv16x_zjdmedam.csv",
        "type": "text/csv",
        "extension": "csv"
      }
    },
    {
      "start_time": "2000-01-01T01:09:17.000Z",
      "end_time": "2000-01-01T01:09:17.000Z",
      "class": "shaken",
      "source_blob": {
        "id": "wm4e2fnqozqczib24eqrl3wamzrhjgyxx6qpyze2a7iykpwuhanq====",
        "metadata": {
          "uuid": "27675a99-3ffe-4cbc-9017-9c333f240a5a",
          "name": "20240212_11_34_06",
          "device_description": {
            "part_number": "STEVAL-MKBOXPRO",
            "serial_number": "005100335752501520353339",
            "alias": "STBOX_PRO_001",
            "fw_name": "FP-SNS-DATALOG2_Datalog2",
            "fw_version": "1.2.1"
          }
        }
      },
      "components": [
        {
          "name": "lsm6dsv16x",
          "sensors": [
            {
              "name": "lsm6dsv16x_acc",
              "type": "Acc",
              "config": {
                "odr": {
                  "value": 480,
                  "unit": "Hz"
                },
                "fs": {
                  "value": 4,
                  "unit": "g"
                }
              }
            },
            {
              "name": "lsm6dsv16x_gyro",
              "type": "Gyro",
              "config": {
                "odr": {
                  "value": 3840,
                  "unit": "Hz"
